name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Install Ionic and Cordova
      run: npm install -g ionic cordova
          
    - name: Checkout
    - uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        ionic build --prod -- --base-href 'https://hoodaajay99.github.io/techskillo/'

    - name: Deploy using github-pages-deploy-action 
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www # The folder the action should deploy.
