name: Build and Deploy Firebase Hosting

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8
        install-java: false
        install-pods: false

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install NPM Modules
      run: |
        npm i -D -E @angular/cli
        npm install
        
    - name: Build
      run: |
        ionic build --prod
        cp ads.txt www/.
        ls www
        
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: techskillo
