

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8

    - name: Checkout
      uses: actions/checkout@v1        

    - name: Build
      run: |
        ionic build --prod -- --base-href 'https://hoodaajay99.github.io/techskillo/'
        ls www

    - name: Deploy using github-pages-deploy-action 
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: www # The folder the action should deploy.