

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v1

    - name: Install Ionic and Cordova
      run: npm install ionic cordova

    - name: Script
      run: ls
